### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by calidion** [w3c/manifest#848] opened 2020-02-05 22:35 UTC
currently manifest only support a string for key `name` and `short_name`.

I would like to suggest, they use i18n based object to represent  i18n strings.

for example:

from 
```
{
name: "An Angular Based Application"
short_name: "angular"
}
```

to 

```
{
name:  {
"en" : "An Angular Based Application",
"zh" : "一个基于角度的程序",
"ja" : "角度ベースのアプリケーション",
}，
short_name: {
"en" : "Angular",
"zh" : "角度",
"ja" : "角度",
}
}
```

**Comment by fallaciousreasoning** [comment] 2020-02-06 03:16
I believe there was some discussion about doing something like this, but I can't find it in any of the other issues.

Related:
#323 #334 #335 #336 #337

From the sounds of things, the resolution on those issues was to serve a different manifest based on the Accept-Language? I guess that doesn't work for changing the language on the OS though.

**Comment by fallaciousreasoning** [comment] 2020-02-06 03:19
Ah, I think this was the issue I wanted: #208

This idea, along with some others are discussed a bit there. The resolution seemed to be "Let's wait for a bit and see what problems come up", so I'll leave this open.

**Comment by fallaciousreasoning** [comment] 2020-02-06 03:19
Note #211 is almost identical.

**Comment by calidion** [comment] 2020-02-06 03:30
`default_locale` or ` languages` is not necessary for the locale devices has defined their locales.
make all strings i18ned.

**Comment by marcoscaceres** [comment] 2022-05-31 03:29
closing as duplicate of https://github.com/w3c/manifest/issues/676

**Closed by marcoscaceres** 2022-05-31 03:29 UTC
Labels: Feature Request, i18n-tracker
