### ISSUE TITLE
Clarify the purpose of `purpose: badge`

### ISSUE THREAD

**Issue by NotWoods** [w3c/manifest#808] opened 2019-10-04 06:44 UTC
The badge purpose is defined as an image to show where "space constraints and/or color requirements differ from those of the application icon". This description is really unclear for both browsers and developers.

The original badge issue (#480) suggested showing the badge in notifications. The web notifications API does already have badge support, but there are other instances where a notification is shown on behalf of the web app. For example, Chrome and Firefox display a site controls notification when a PWA is open.

<img src="https://user-images.githubusercontent.com/1782266/66186374-f08e7080-e636-11e9-978b-ca5dfa01c5f1.png" alt="Site controls notification" height="500">

`badge` icons could potentially be displayed instead of a generic icon.

<img src="https://user-images.githubusercontent.com/1782266/66186434-19af0100-e637-11e9-8569-aa8d25465fcb.png" alt="Badged site controls notification" height="500">

[Shortcut icons](https://github.com/w3c/manifest/issues/795#issuecomment-532950542) may also need a way to define a specialized icon and badge could potentially be used there if better defined.

I think a good definition to move towards would be that badge corresponds to a monochrome icon, where only the alpha channel is used by the user agent. Colors would be ignored. This behaviour is similar to how Android treats a notification icon asset. 

Monochrome icons are used in a couple different browsers already. Safari has [pinned tabs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html) on the touchbar using the `mask-icon` name.
![Screen Shot 2019-10-03 at 11 49 11 PM](https://user-images.githubusercontent.com/1782266/66186932-6e9f4700-e638-11e9-922e-ee6ee061221a.png)

Windows 8 and 10 usually shows white icons on a colored background for tiles in the start menu. 
![w8_home_screen](https://user-images.githubusercontent.com/1782266/66186996-968eaa80-e638-11e9-96a4-16d21d300ffa.png)

It might be best to rename `badge` to `monochrome` (or something else) in this case. This would match how `maskable` is named after the asset type, not where the asset is used.

**Comment by mgiuca** [comment] 2019-10-04 07:28
Thanks @NotWoods . This is a really good summary with examples and screenshots on different platforms.

I think this is a dupe of #808 where there's already been a fairly lively discussion including my rough proposal for a more specific spec for "badge". I also would be open to renaming it to `monochrome` (or just adding a new `monochrome` purpose) since that's how I'd like this to be used.

Shall we continue discussion on #808?

**Closed by mgiuca** 2019-10-04 07:28 UTC

**Comment by NotWoods** [comment] 2019-10-04 15:18
My impression is that #795 refers to only [shortcuts](https://github.com/w3c/manifest/pull/768) while this issue refers to the badge/monochrome purpose. (Although there's been discussion for specifically badge in that issue.) The 3 scenarios above are all examples of where badge could be used that are not shortcuts.
