### ISSUE TITLE
i18n: No means of obtaining correctly localized manifest; [I18N-ISSUE-414]

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#336] opened 2015-03-20 08:11 UTC
http://www.w3.org/International/track/issues/414

Raised by Addison Phillips

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#obtaining

Section 6.1 discusses the steps in obtaining a manifest. There is no discussion of obtaining a correctly localized reference, particularly for use in cases where the source page itself has used language negotiation.

**Comment by marcoscaceres** [comment] 2015-03-25 15:40
AFAICT, we can't specify a "correct" method - we can only suggest normal means of fetching a URL via a `link` element (or `Link` HTTP header).

**Comment by marcoscaceres** [comment] 2015-04-27 17:44
Duplicate of https://github.com/w3c/manifest/issues/323

**Closed by marcoscaceres** 2015-04-27 17:44 UTC
Labels: I18N-WG

**Comment by himorin** [comment] 2021-01-29 10:31
Note: W3C i18n WG closed our tracker with actions taken satisfactory. (please not remove i18n-needs-resolution label which is used by our bot and tracking system)
