### ISSUE TITLE
i18n: No localized examples; [I18N-ISSUE-413]

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#337] opened 2015-03-20 08:11 UTC
http://www.w3.org/International/track/issues/413

Raised by Addison Phillips

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#example-manifest 

There is an example of a manifest, but no example of non-English or non-ASCII data. Please consider adding some of each.

**Comment by marcoscaceres** [comment] 2015-03-20 19:24
Duplicate of https://github.com/w3c/manifest/issues/323

**Closed** 2015-04-27 17:46 UTC
Labels: duplicate, I18N-WG
