### ISSUE TITLE
What's the use case for theme_color?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/manifest#356] opened 2015-04-07 22:34 UTC
```theme_color``` in the Manifest sounds fairly odd. Discussing with @PaulKinlan and @marcoscaceres, my understanding is that it was meant as a defaul theme_color for the meta tag. However, this is not possible because the UA might want to have a theme_color value for the first paint but Manifest can't block the first paint.

I would understand that it could be used for UI-related features but I would prefer to avoid keeping things in the Manifest "in case of". Is there interest to use theme_color by an implementation?

**Comment by marcoscaceres** [comment] 2015-04-07 22:50
I was wanting to use it to generate cells when you open a new tab in the browser. That is, I want to have a background color and an icon that I can show at "about:newtab" instead of screenshots.

**Comment by marcoscaceres** [comment] 2015-04-07 22:50
Don't know if theme_color is the best thing for that... but... it could work.

**Comment by kenchris** [comment] 2015-04-08 05:50
Also suggested by @slightlyoff here https://github.com/slightlyoff/AppInstallImprovements

**Comment by PaulKinlan** [comment] 2015-04-08 12:42
Originally I wanted themecolor as a manifest defined attribute that would color and theme all the browser chrome (progress bars, alerts etc) for an app that had just been installed.  I was thinking specifically about the sites where there is a lot of content and adding a meta tag across all pages is a pain, it would mean that you wouldn't pop-out of the brand experience whilst navigating the site in a full-screen mode.

I don't believe there is that much interest in theme-color for that use-case on the Chrome side.

**Comment by marcoscaceres** [comment] 2015-04-08 15:31
Ok, let's back out `theme_color` for now. For splash screen, we can add a `bg_color` member.

**Comment by slightlyoff** [comment] 2015-04-08 23:45
I DO think this is interesting and I'd rather see it here than in meta
tags. Can we *not* remove it?

**Comment by marcoscaceres** [comment] 2015-04-22 20:57
We can keep it. Maybe I should add a flag that it's at risk tho.

**Comment by kenchris** [comment] 2015-04-28 16:06
Just wanted to point out that the feature does make sense for apps submitted to app stores, or who have been added to home screen, as the value will be available at launch and thus before the meta tag is read

**Comment by Tigt** [comment] 2015-05-12 00:10
I like the idea of it being themed throughout the OS this way. Are there any existing examples of doing this with native apps? I would much prefer having installed-app information in the one manifest file, instead of it being spread onto the page, too.

(This isn't to slam the existence of `meta[theme-color]`, since having it as an individual page override is also useful.)

**Comment by martinkearn** [comment] 2015-06-25 04:15
Please do not remove this. I use the manifest to drive production of native apps for windows. My icons are pngs files with transparent backgrounds and I use theme colour to set the background colour for all my icons and app splash screen. Without theme colour, I would have to reproduce all the icons if I ever wanted to change the theme of the app. I think there are several clear use cases for this and would not like to see it removed.

**Comment by boyofgreen** [comment] 2015-09-17 15:37
I noticed this marked as removal.  We are using this from a windows 10 perspective.  Some colors (app bars) can be set programmatically in the js, but the "pre launch" items like splash and image bg colors do require us to have a value in the manifest.  Let me know if you need more details

**Comment by kenchris** [comment] 2015-09-19 12:28
It is also supported by Chrome for similar use-cases, so it should not go away.

**Comment by marcoscaceres** [comment] 2015-09-19 14:45
@boyofgreen, @kenchris, agree; people have found plenty of use cases for it now, so will remove the banner.

**Closed** 2015-09-21 09:29 UTC
Labels: question
