### ISSUE TITLE
Properties not mentioned in the Spec - Safe to use?

### ISSUE THREAD

**Issue by ayumihamsaki** [w3c/manifest#711] opened 2018-08-24 17:28 UTC
See the following two webpage examples:

In Google Developers Page found here: https://developer.chrome.com/apps/manifest

In FireFox MDN Web Docs found here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_compatibility_for_manifest.json

As you can see there are many properties not mentioned in the Spec's. Some questions jump into my mind to ask:

1. Is it safe to use Properties not mentioned in the Spec?
1.a) Can Browsers Still Read the Data in the Manifest File if the Property is not Supported (yet).
1.b) Would w3c add something to the spec to stop that, or block it or something else related in that respect.
2. Will these Properties be added to the Spec at a later date - I do understand its still in Draft. However, there are so many good Properties out there that would seem to have some good benefit to be added.

These are my main questions but I am sure people would have lots more questions to this!

* Personally I would love to see many of these new properties in the Manifest File. Things like `author`, `description`, `developer` etc. Would be nice to move `humans.txt` into the manifest file.

**Comment by marcoscaceres** [comment] 2018-08-27 03:37
> As you can see there are many properties not mentioned in the Spec's. Some questions jump into my mind to ask:

oh, I think that manifest file is for browser extensions (WebExtensions), not for "web manifest"... it just happens to be called the same thing. 

I added a warning at the top of that page. 

> 1.a) Can Browsers Still Read the Data in the Manifest File if the Property is not Supported (yet).

Yes - see below. 

> 1.b) Would w3c add something to the spec to stop that, or block it or something else related in that respect.

No, because browsers just ignore things they don't understand (by design) - similar to how parsing CSS works. 

> Will these Properties be added to the Spec at a later date - I do understand its still in Draft. However, there are so many good Properties out there that would seem to have some good benefit to be added.

No - that's a different format ... just share the file name and some of the same property names.

>  Things like author, description, developer etc. Would be nice to move humans.txt into the manifest file.

We've considered this in the past, but as `humans.txt` already exists, we decided not to duplicate it. 

As a general rule, we only add manifest properties if they have some direct effect on the OS (e.g., "`icon` sets the icon for the app, `name` sets the name of the app"), or browser (e.g., "`orientation` changes the orientation"). Things like `author`, `description` and other metadata don't seem to have any demonstrable utility in either the browser or the OS.

**Comment by marcoscaceres** [comment] 2018-08-27 03:37
Closing as answered.

**Closed by marcoscaceres** 2018-08-27 03:37 UTC
Labels: question

**Comment by ayumihamsaki** [comment] 2018-08-29 18:35
@marcoscaceres Thank you for taking the time to answer all my questions!
