### ISSUE TITLE
i18n: No language metadata for 'name'; [I18N-ISSUE-415]

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#335] opened 2015-03-20 08:10 UTC
Raised by Addison Phillips

http://www.w3.org/International/track/issues/415

http://www.w3.org/TR/2015/WD-appmanifest-20150212/#name-member

The 'name' manifest member does not provide a way to indicate the language of the string. This may be necessary for proper presentation/rendering of the name, since, for example, different fonts might be selected for different languages (such as when selecting between Japanese and Chinese).

**Comment by marcoscaceres** [comment] 2015-03-25 15:42
Duplicate of https://github.com/w3c/manifest/issues/322 ? I.e., we don't provide a mixed method of doing languages with this format.

**Comment by pornel** [comment] 2015-04-06 07:55
I suggest dropping the redundant `name` property and using the existing [application-name](https://html.spec.whatwg.org/multipage/semantics.html#meta-application-name) instead, which is localizable thanks to `lang` and `dir` attributes.

**Comment by marcoscaceres** [comment] 2015-04-06 19:36
Might be too late to drop name.

**Comment by marcoscaceres** [comment] 2015-04-27 17:45
Duplicate of #323

**Closed by marcoscaceres** 2015-04-27 17:45 UTC
Labels: I18N-WG

**Comment by himorin** [comment] 2021-01-29 10:30
Note: W3C i18n WG closed our tracker with actions taken satisfactory. (please not remove i18n-needs-resolution label which is used by our bot and tracking system)
