### ISSUE TITLE
Add optional indication of Service Workers to Manifest

### ISSUE THREAD

**Issue by RobDolinMS** [w3c/manifest#447] opened 2016-04-07 22:08 UTC
BACKGROUND: There are some uses cases where apps (often multiple apps) are downloaded/installed/pinned at one time and then not run until a later time.  For example:
•	User is browsing a catalog or list of apps and selects multiple web apps to install
•	User is restoring a device and all previous apps are installed

If the first run of the web app happens when the user is offline, web app developers who have invested in offline technologies like Service Workers still want the end user to have a good experience. 

PROPOSAL: Enable Web App Manifest authors to (optionally) specify Service Workers that should be instantiated when an app is installed; AND enable these Web App Manifest authors to also indicate if each Service Worker requires individual user credentials

FAQ:
Q: What about Service Workers that require individual user credentials?
A: These Service Workers can be indicated in the manifest so the user agent knows whether or not to instantiate these anonymously

**Comment by kenchris** [comment] 2016-04-08 08:37
For the new install event (what @marcoscaceres is working on) to work, somehow some code would need to run when being installed. If that is more general purpose that JS code could install the service worker.

Or would it make sense to have the install event on the service worker, so that the service worker (plus its install step) is the only requirement in addition to the manifest file itself?

Issues: Service Workers take arguments (just scope right now but that could change) and with foreign fetch to, say the "additional_scopes", more service workers might be required

**Comment by marcoscaceres** [comment] 2016-04-14 01:50
Duplicate of #161.

@RobDolinMS, would be great to continue the discussion in #161 instead. We can reopen that issue if need be.

**Closed by marcoscaceres** 2016-04-14 01:50 UTC
