### ISSUE TITLE
Please add caption property to screenshots

### ISSUE THREAD

**Issue by SpeednetGroup** [w3c/manifest#773] opened 2019-07-24 18:12 UTC
Since `screenshots` is intended to be used by app stores, and because all app stores use textual captions associated with each screenshot, we need to add a `caption` (or perhaps `description`) string property to each screenshot object.

As it stands right now, you can just define a bunch of screenshots that will get displayed in an app store without any context or description.

Of course, `caption` can be an optional property.

**Comment by marcoscaceres** [comment] 2019-07-30 05:48
We are actually considering dropping screenshots entirely (and metadata that would be ingested by stores). These fields didn't end up getting used anywhere and are obviously not used by browsers.

**Comment by SpeednetGroup** [comment] 2019-07-30 11:40
I hope not, we didn't even know about screenshots until a week ago and I'm sure a lot of other developers don't know about it.  The popular tutorials and PWA blogs/articles don't mention it -- a well kept secret.

**Comment by marcoscaceres** [comment] 2019-07-30 11:43
Kinda a good thing then... less damage if we do remove it. Again, the problem is lack of support from anyone that we know of... although, we need to check with the Microsoft Store, as these requests came from them I think (but not sure if they ever added support or not).

**Comment by marcoscaceres** [comment] 2019-07-30 11:43
@aarongustafson, do you know what the story is with `screenshot`? It is supported at all by some Microsoft property?

**Comment by jgw96** [comment] 2019-07-30 20:13
I cant speak to the level of detail about this that Aaron can, but wanted to add my 2 cents that I do know that screenshots are important to us at Microsoft for our store experience. Also, speaking for my team at least at Microsoft, we have been experimenting with screenshots and want to start publicizing them more as a useful way to improve even the default install experience in browsers like Chrome and the new Edge.

**Comment by aarongustafson** [comment] 2019-07-30 20:37
Yep, I'll echo what @jgw96 said. We do use screenshots for the Store currently and are actively investigating ways to make that (and categories, etc.) more visible to end users within a browser context.

**Comment by dominickng** [comment] 2019-07-30 21:46
Specifically, does Edge actually parse the screenshot member and extract detail from it? It would be good to know the specific level of support for this member you have. :)

**Comment by aarongustafson** [comment] 2019-07-31 04:12
@dominickng We are not currently using it in Edge though, as @jgw96 said, we are experimenting with them in the context of Edge. We are actively using the key in the Microsoft Store. Other PWA "app stores" are also including screenshots as well (e.g., [AppScope](https://appsco.pe/), [PWA Store](https://www.pwastore.com), etc.). This seems like an area that is still growing and being explored. As evidenced by @SpeednetGroup’s comment, many devs don’t know it exists—perhaps because [the Google docs](https://developers.google.com/web/fundamentals/web-app-manifest/) don’t include it?—and I suspect as PWAs show up in more traditional "app stores" this key will become more valuable.

For context of how we are using `screenshots` in the Microsoft Store, I cover that in a few of my PWA talks. Here’s [one reference I was able to find quickly, from May of 2017](https://www.aaron-gustafson.com/notebook/progressive-web-apps-and-the-windows-ecosystem/):

> Regardless, whether they got their by passive ingestion or my manual submission, the Web App Manifest will provide the basic set of information used for the app in the Store: name, description, icons, and screenshots. We’re also actively working with others in the W3C to introduce support for app categories and IARC ratings.

To @SpeednetGroup’s original point, I agree that a `description` (or similar key) would be a beneficial addition in this context, for both sighted and non-sighted users.

**Comment by marcoscaceres** [comment] 2019-07-31 04:32
@aarongustafson, that's really exciting to hear it's being used! We were a little worried that it wasn't - so definitely keep in the spec then. Then yes, I agree that having a description of the image makes sense.

**Comment by aarongustafson** [comment] 2019-09-19 00:31
Open to discussing this [@ TPAC today or tomrrow](https://github.com/w3c/webappswg/issues/10).

**Comment by aarongustafson** [comment] 2020-05-11 23:20
Closing in favor of https://github.com/w3c/image-resource/issues/7

**Closed by aarongustafson** 2020-05-11 23:20 UTC
Labels: Feature Request
