### ISSUE TITLE
Support for platform hints on icons

### ISSUE THREAD

**Issue by owencm** [w3c/manifest#405] opened 2015-09-26 00:40 UTC
Looking at Slack's website the other day I noticed just how different icon standards are for different platforms:

<img width="1101" alt="screen shot 2015-09-25 at 5 29 22 pm" src="https://cloud.githubusercontent.com/assets/279720/10114742/31a137b4-63ab-11e5-8af5-bfcbd9f91472.png">

I wonder if we should support the ability for sites to optionally hint a specific icon is more suitable to a certain platform. For example the manifest could provide default icons in different sizes in the way today, and additionally versions with a new property like `suggested_platforms` containing a list of strings corresponding to platforms that icon would be well suited for.

I'm not sure of the best way for us to standardize (or leave unstandardized?) platform strings though so UAs know which OS to apply them on - naively we could define a short list and add ones as they request to be added, but that seems potentially difficult. Also it's unclear to me whether we'd want to support versioning (e.g. 'win10' vs 'win' etc).

**Comment by marcoscaceres** [comment] 2015-09-26 01:26
@owencm thanks for the additional input + example! This is a duplicate of https://github.com/w3c/manifest/issues/361. Please take a look. 

FWIW, we are planning on adding `platform`. Just waiting for Gecko to catch up.

**Closed** 2015-09-26 01:26 UTC
Labels: duplicate
