### ISSUE TITLE
All String should be localizable

### ISSUE THREAD

**Issue by calidion** [w3c/manifest#1136] opened 2024-06-25 07:39 UTC
All manifest strings can be able to use localized strings for internationalization.
They should support at lease two types of definitions:

1. Direct one string for one language only
```
"name":  "Web App"   // English only
```
or 
```
"name":  "网站应用"  // Chinese Only
```
3. Multiple languages support 
```
lang: "en",   // fallback language if browser meets none locale strings listed
"name":  {
"en":  "Web App",    // fallback for all en-* browsers or for general  en-* users
"en-US":  "Web App",   // specific string for localized en
"zh": "网站应用”， // fallback for all zh-* browsers  or for general  zh-* users
"zh-CN": "网站应用”， // specific string for localized zh
...
```

**Comment by christianliebel** [comment] 2024-06-25 07:56
@calidion Thank you for reporting this issue. We are currently addressing this scenario as part of PR #1101. Feel free to subscribe to this PR and join the discussion there. I will close this issue as a duplicate of #676.

**Closed by christianliebel** 2024-06-25 07:56 UTC
