### ISSUE TITLE
More restrictive standalone mode

### ISSUE THREAD

**Issue by madmoizo** [w3c/manifest#770] opened 2019-06-30 10:50 UTC
I'm playing with Edge canary on desktop and `standalone` mode is congested with UA specific UI (translation button, password manager button, back button) 
![image](https://user-images.githubusercontent.com/11896237/60662676-519e8080-9e5d-11e9-96ff-63190da035ef.png)

https://www.w3.org/TR/appmanifest/#display-modes
Problem is, the `standalone` description is very permissive:
> the user agent will exclude standard browser UI elements such as an URL bar, but can include other system UI elements such as a status bar and/or system back button.

minimal-ui says:
> This mode is similar to standalone, but provides the end-user with some means to access a minimal set of UI elements for controlling navigation (i.e., back, forward, reload, and perhaps some way of viewing the document's address). A user agent can include other platform specific UI elements, such as "share" and "print" buttons or whatever is customary on the platform and user agent.

On desktop, I expect a basic OS window from the `standalone` mode but the spec definition can lead to a `minimal-ui-light` mode.
So, Is it possible to be more restrictive about the `standalone` mode ?
For example, suggest that invasive UA controls (back button) remain hidden by default

**Comment by aarongustafson** [comment] 2019-06-30 15:01
Is that translate button a plug-in?

**Comment by frlinw** [comment] 2019-06-30 15:56
@aarongustafson Not at all, basic Edge canary installation, but its display is probably conditional.

**Comment by marcoscaceres** [comment] 2019-07-01 03:56
@frlinw, W3C specs generally don't impose UI requirements on user agents (by design), as UI differences is what browsers mostly compete on. We (browser vendors) are still investigating how to best build UIs for installable web apps. I believe we even have a spec bug around requesting or getting rid of the back button in the UI. Bottom line is that we are still figuring this stuff out.  

Nevertheless, no doubt the Edge Team (via @aarongustafson) appreciate your feedback - though please be mindful not to use words like "bloated", etc. A lot of thought goes into those UI decisions.

**Comment by frlinw** [comment] 2019-07-01 10:20
@marcoscaceres of course, I just wanted to clarify a possible overlap between `standalone` and `minimal-ui` which can be confusing for browser vendors too (all are not involved in the spec definition & intern discussions, right?)

As you probably noticed, english is not my native language, I had no intent to be rude, sorry for that. I'll pay more attention to the words used.

**Comment by aarongustafson** [comment] 2019-07-01 23:04
@frlinw I suspect the translate icon appearing is a bug (I’m researching internally as I have not seen it myself). For standalone & minimal-ui, we (Edge) have been thinking about extras like Translate, plugins, etc. as things users may want to persist from the browser to their PWAs, but in the triple dot/ellipsis (…) menu rather than the toolbar.

**Comment by frlinw** [comment] 2019-07-01 23:41
@aarongustafson It's consistent with the in-browser address bar at least
![image](https://user-images.githubusercontent.com/11896237/60472181-18e98600-9c68-11e9-8495-396f6d990b8d.png)
Try the URL if you want to reproduce.

> in the triple dot/ellipsis (…) menu rather than the toolbar.
It would be perfect that way

Anyway, Edgemium is great, keep up the good work. Easy app management is now a must-have for me
![image](https://user-images.githubusercontent.com/11896237/60472351-deccb400-9c68-11e9-805f-3ac13531f7e7.png)

**Comment by frlinw** [comment] 2019-07-05 18:23
After trying Twitter webapp, it seems password manager icon is conditional too. I don't understand why it doesn't hide after login on my own webapp. What is the rule ?

**Comment by marcoscaceres** [comment] 2024-06-06 23:43
Going ahead and closing this one as reviewing it, it's specific to browser UI.... the spec can't really say what can and can't go into the browser UI, and in any mode, the browser may put whatever it likes into any menu bars, status bars, etc.

**Closed by marcoscaceres** 2024-06-06 23:43 UTC
Labels: Feature Request, Defer
