### ISSUE TITLE
Is it possible to load the progressive web app manifest file from authenticated site?

### ISSUE THREAD

**Issue by svdoever** [w3c/manifest#535] opened 2016-12-06 01:15 UTC
I'm having the progressive web app index.html page and assets in a SharePoint document library. I need to authenticate when accessing the index.html page. But the manifest.json file as linked as <link rel="manifest" href="manifest.json.txt"> does not have the required authentication cookie when requested from the index.html page. Note that SharePoint does not serve .jon files, that is why it ends with .txt. Is there a way to retrieve the manifest from an authenticated site?

It works when I have the manifest on an anonymously accessible location, i.e. outside of SharePoint (I now use my dropbox). In that case I need to specify a full path for the start_url. But this is not a really nice deployment model because I need to deploy files to two different locations...

**Comment by marcoscaceres** [comment] 2016-12-06 12:49
This also sounds like a bug in Chrome: loading manifest should send the same information along as any other `<link>`ed resource.

**Comment by RobDolinMS** [comment] 2016-12-06 21:55
@svdoever Building on @marcoscaceres's suggestion, would you please try testing in Edge, Internet Explorer, and/or Firefox and let folks know if the issue can be reproduced in multiple web browsers.

**Comment by dominickng** [comment] 2016-12-07 02:34
I believe that you must specify crossOrigin="use-credentials" in the manifest link tag to allow the manifest fetch to use cookies and credentials in Chrome.

**Comment by svdoever** [comment] 2016-12-07 16:59
@dominickng you are a hero! crossOrigin="use-credentials" did the job!

**Comment by dominickng** [comment] 2016-12-08 00:17
Closing as fixed. :)

**Comment by marcoscaceres** [comment] 2016-12-08 00:25
Thanks @dominickng! My bad for assuming it was a bug in Chrome.

**Comment by svdoever** [comment] 2016-12-11 13:40
I still think that all hrefs to same domain should get the authentication headers passed through... other assets can be loaded without the crossOrigin property.

**Comment by marcoscaceres** [comment] 2017-01-25 06:11
I need to check what HTML says. Ideally, I'd like to just follow whatever it says to do wrt loading resources from link relationships.

**Comment by HolgerJeromin** [comment] 2018-11-02 10:52
This behavior is still surprising to me and others.

**Comment by mgiuca** [comment] 2018-11-05 02:29
Since this isn't a spec issue, transferring this to https://crbug.com/901705.

**Closed by mgiuca** 2018-11-05 02:29 UTC

**Comment by mgiuca** [comment] 2018-11-05 02:45
OK we had a closer look (with @dominickng). This _is_ a spec issue, because the Manifest spec explicitly overrides HTML's "Obtaining a resource from a link element" algorithm.

https://www.w3.org/TR/appmanifest/#obtaining

So while normal `<link>` elements send credentials by default, `<link rel="manifest">` explicitly does not. This appears to be intentional because it's secure by default, whereas retrofitting it for other link types like icons and style sheets was not possible.

For historical discussions, see:

- https://bugs.chromium.org/p/chromium/issues/detail?id=863218#c14
- https://github.com/w3c/manifest/issues/186#issuecomment-43798231
- https://github.com/w3c/manifest/issues/17#issuecomment-43808117

Looks like this has all been litigated in 2014 and a conclusion was made to override the default behaviour of HTML. Keeping this closed as I don't think it's worth going over this again.

**Comment by marcoscaceres** [comment] 2018-11-05 04:31
Thanks for doing the archeology on it!

**Comment by ezekielchentnik** [comment] 2019-01-02 02:57
Thanks for the archeology, needed this today.  Cheers.
