### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by ghost** [w3c/manifest#575] opened 2017-05-08 11:08 UTC
Under Android 7.1 it's possible to add shortcuts to the most important features of an app.
https://developer.android.com/guide/topics/ui/shortcuts.html
 It would be very useful for web apps too. This could benefit not only the user when he long presses the icon on the home screen, but also search engines and app stores, which can display these shortcuts to give direct access to the main features of an app.

```
"shortcuts": [{
    "long_label": "New conversation",
    "short_label": "New",
    "icon": "/images/plus.svg",
    "url": "/conversations/new"
}, {
    "long_label": "Search conversation",
    "short_label": "Search",
    "icon": "/images/magnify.svg",
    "url": "/conversations/search"
    }
]
```

**Comment by marcoscaceres** [comment] 2017-05-09 04:53
Any idea if Chrome plans to support this? Maybe we will hear about it at IO?

**Comment by kenchris** [comment] 2017-05-09 07:18
No idea, we will just have to wait and see :)

**Comment by dominickng** [comment] 2017-05-09 07:20
@owencm thoughts? Seems like it could be an interesting and useful addition.

FYI, Chrome has only just migrated to the Android 7.1 shortcut API, so we haven't really thought too deeply about this yet.

**Comment by kenchris** [comment] 2017-08-11 16:48
Relevant links:

https://docs.google.com/document/d/1jWLpNEFttyLTnxsHs15oT-Hn8I81N0cwUa3JjISoPV8/edit#
https://gist.github.com/kenchris/0acec2790cd38dfdff0a7197ff00d1de

**Comment by kenchris** [comment] 2018-02-22 18:04
Duplicate of #582

**Closed** 2018-02-22 18:04 UTC
Labels: Feature Request
