### ISSUE TITLE
Required WebAppManifest Member clarification

### ISSUE THREAD

**Issue by moonmeister** [w3c/manifest#799] opened 2019-09-20 02:17 UTC
I'm working on building a validator for this spec and have found the definition for "required" members very vague. [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Manifest) marks several members as required but the `WebAppManifest` dictionary on the spec page indicates no required top level members (there are some in the `ImageResource ` dictionary and others). 

Is this correct that no member of the `WebAppManifest` dictionary is required? 

If this is the case maybe it's worth come kind of clarification statement somewhere in the spec.

Thanks!

## Related Issues:

#24

**Comment by mgiuca** [comment] 2019-09-20 03:31
I think this is a dupe of #622 (which was just closed an hour ago but I just reopened it).

> [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Manifest) marks several members as required

I don't see any indication on that page of "required" members.

The only member that we can plausibly "require" is `name`. Since manifest can be applicable to both decorating a document (e.g., with theme color) as well as for installability, there aren't really any fields that are necessary to both of those cases. Let's discuss requiring `name` on #622.

**Closed by mgiuca** 2019-09-20 03:31 UTC

**Comment by moonmeister** [comment] 2019-09-20 03:52
thanks for the response!

MDN marks these as "Mandatory":
- [name](https://developer.mozilla.org/en-US/docs/Web/Manifest/name)
- [icons](https://developer.mozilla.org/en-US/docs/Web/Manifest/icons)
- and [serviceworker](https://developer.mozilla.org/en-US/docs/Web/Manifest/serviceworker) until i edited it yesterday ([see prev](https://developer.mozilla.org/en-US/docs/Web/Manifest/serviceworker$revision/1568883 )).

While #622 is related it's a different question. I'm asking for clarification on the current status, and for clarify language of the current state to be added. It sounds like the answer might be: currently no member is required (that may change in the future based on #622 ). 

Is this correct?

Thanks!

**Comment by mgiuca** [comment] 2019-09-20 04:00
Interesting that serviceworker was mandatory! (It certainly wasn't, since [nobody has ever implemented it](https://github.com/w3c/manifest/issues/800).)

Yeah I think the right answer is that no field is absolutely mandatory of the manifest. However, many fields are required by certain processors in order to be accepted as a valid app. For example, Google Chrome (according to [this](https://developers.google.com/web/fundamentals/app-install-banners/)) requires (at least) the following in order to show an install banner:

- `name` or `short_name`
- `icons`
- `start_url`
- `display` set to something other than `browser`

It wouldn't be correct to say these are mandatory in the manifest itself. But they are required by that user agent. I have always wanted us to create a standard definition of a "PWA" so we can standardize across browsers, but in the mean time, each user agent has its own possibly conflicting set of requirements to be installable.

If you're writing a validator, you may want to take these into account, but there's a nuance to it beyond just "invalid" / "valid".

**Comment by moonmeister** [comment] 2019-09-20 04:06
Thanks! yeah, I saw some of that on Chrome's docs. For my use cause sticking with spec is fine because we're not trying to tell user's what to be compatible with. I've debated extracting the `@hapi/joi` object out into an NPM package for use by others. If I do so, I could create modified versions that are browser specific or just throw a warning on validation that not including something means it won't be compatible with a specific browser.
