### ISSUE TITLE
IDL: Make name required

### ISSUE THREAD

**Issue by kenchris** [w3c/manifest#622] opened 2017-10-10 09:40 UTC
And look whether other properties need to be so too

**Comment by aarongustafson** [comment] 2019-09-20 01:42
The associated PR was merged. We can close this, right @kenchris?

**Comment by mgiuca** [comment] 2019-09-20 03:24
But that associated didn't address the issue; this was filed [in response to a comment on there](https://github.com/w3c/manifest/pull/613#discussion_r142580369).

I think name possibly should be required.

**Comment by mgiuca** [comment] 2019-09-20 03:28
Looks like this was already litigated in 2013: #24 

I think the issue is that we don't want to drastically error out if there's no name, but we still want to "require" it in what we consider a "valid" manifest. (Similar to how HTML `<title>` is technically required, but obviously agents still display a document if it's present.)

@marcoscaceres Perhaps you can define this better in the new parser that you're working on. The "correct" thing to do here is to a) define a "valid" manifest, and b) define the user agent behaviour if the manifest is invalid, which may not be fatal; e.g., we may still accept a manifest that has no name but the site may not be installable.

**Comment by aarongustafson** [comment] 2019-09-20 04:57
@mgiuca I can get behind that.

**Comment by marcoscaceres** [comment] 2020-05-25 08:47
this is in the spec already (at least, option 2 is)... will link it up properly.

**Comment by christianliebel** [comment] 2020-07-07 06:48
@marcoscaceres What needs to be done here?

**Comment by marcoscaceres** [comment] 2020-07-15 06:06
I still don't think we want to require name, tbh... some UAs may have criteria that invalidates a manifest without a name, but others might not. Safari, for instance, is perfectly happy to let you install a web application without a name.

**Comment by marcoscaceres** [comment] 2020-07-15 06:06
s/invalidates a manifest without a name/considers the manifest to not be installable

**Comment by aarongustafson** [comment] 2020-07-15 06:37
Without it, users would end up with a less accessible app icon though, no?

**Comment by marcoscaceres** [comment] 2020-07-15 07:34
Not necessarily, the name can still be derived from the document's application-name, title, or given a system default like "untitled" (or the user can rename it).

**Comment by aarongustafson** [comment] 2020-07-15 14:08
Sounds good. Let's document that.

**Comment by marcoscaceres** [comment] 2020-07-16 04:42
It's currently in the [authority section](https://www.w3.org/TR/appmanifest/#authority-of-the-manifest-s-metadata): 

> in cases where metadata is missing, or in error, a user agent MAY fallback to the Document to find suitable replacements for missing manifest members (e.g., using application-name in place of short_name).

But it may be good to actually move the above to the "application name" section.

**Comment by mgiuca** [comment] 2020-07-17 04:00
Hmm. #668 which I am trying to solve is working towards having the manifest not depend on the document for processing.

I would rather not spec that the manifest's name falls back to the document. That is even more of a dependency on the document than we have now, which moves us away from being able to say "install this manifest" (without being in a document).

I'm happy to keep a MAY that says the user agent can get stuff from the document. As discussed on #834, that's unavoidable given that user agents invent an entire manifest if installing a page without one, but I want to keep that as a user agent feature, and have the core manifest processing algorithm not rely on a document.

**Comment by marcoscaceres** [comment] 2020-07-17 08:50
> I'm happy to keep a MAY that says the user agent can get stuff from the document.

Yeah, what's currently there (https://github.com/w3c/manifest/issues/622#issuecomment-659154431) is sufficient IMO. It gives the UA flexibility and doesn't tie it to the document.

**Comment by aarongustafson** [comment] 2021-01-22 23:00
Once #927 lands, shall we make this change?

**Closed** 2021-01-22 23:04 UTC
Labels: Editorial clarification, has pullrequest
