### ISSUE TITLE
"This version" link => 404

### ISSUE THREAD

**Issue by alrra** [w3c/manifest#354] opened 2015-04-07 22:31 UTC
> This version: http://www.w3.org/TR/2015/WD-appmanifest-20150408/

![](https://cloud.githubusercontent.com/assets/1223565/7035168/c239da40-dd8e-11e4-8299-909b1e09777d.png)

```bash
$ curl -sSLI http://www.w3.org/TR/2015/WD-appmanifest-20150408/

HTTP/1.1 404 Not Found
Date: Tue, 07 Apr 2015 22:27:47 GMT
Server: Apache/2
P3P: policyref="http://www.w3.org/2014/08/p3p.xml"
Content-Length: 6859
Content-Type: text/html;charset=utf-8
```

**Comment by marcoscaceres** [comment] 2015-04-07 22:34
Strange... will have the W3C have a look.

**Comment by marcoscaceres** [comment] 2015-04-27 17:48
@astorije, can you provide some guidance here? It seems this happened when Echidna was first made public, but I don't have any way of fixing this on TR.

**Comment by astorije** [comment] 2015-04-27 18:44
Hi @marcoscaceres, sorry I'm not sure to see what is your issue here.

The latest version of appmanifest points to http://www.w3.org/TR/2015/WD-appmanifest-20150407/, which might be what you are looking for, no?

**Comment by marcoscaceres** [comment] 2015-04-27 21:41
@astorije, sorry for not being clear. The problem is that if you go to:

http://www.w3.org/TR/2015/WD-appmanifest-20150317/

The current version and the previous version are the same. So you can't go back any further by following the "previous versions" link.

**Comment by astorije** [comment] 2015-04-27 22:40
@marcoscaceres, oups, sorry! Yes it was a bug in Echidna when using the spec-generator, I hope no other documents were affected (please let me know if you encounter other documents like this).

It's fixed now, let me know if something else looks wrong to you.

**Comment by marcoscaceres** [comment] 2015-04-27 22:41
@astorije looks good! thank you!

**Closed by marcoscaceres** 2015-04-27 22:41 UTC
Labels: bug
