### ISSUE TITLE
Allow sub-domains in manifest scope ?

### ISSUE THREAD

**Issue by sach2211** [w3c/manifest#631] opened 2017-12-07 10:32 UTC
Currently the scope defined in web-manifest can be set to current origin, but does not allow other  subdomains of current origin or other domains.

This causes users to 'move out' of the standalone mode of the web app, when navigating to a different subdomain.

Referring to some discussion on this topic, I realized there are some security reservations around allowing other domains in scope, but, can there be an option to atleast set scope to all subdomains of current origin ?

**Comment by RobDolin** [comment] 2017-12-07 14:45
Thanks @sach2211.  There was some discussion related to this in #449 (Allow for multiple scopes)

**Comment by marcoscaceres** [comment] 2017-12-08 06:09
Closing a duplicate of #449 as we discussed it fairly extensibly there.

**Closed by marcoscaceres** 2017-12-08 06:09 UTC
