### ISSUE TITLE
Graceful handling of no network connectivity in hosted apps

### ISSUE THREAD

**Issue by dvonlehman** [w3c/manifest#339] opened 2015-03-23 18:11 UTC
Would be great to have a mechanism to gracefully handle the case when a hosted app is launched which requires a network connection to function and the `start_url` fails to load within a configured timeout interval. If the OS knows up front there is no network connectivity and the app has signaled that a network connection is required, then don't bother attempting to load the `start_url` at all. 

Perhaps the manifest supports a `network_unavailable_url` member which is loaded in this scenario. The OS would need to cache this URL each time the app does load successfully (or at least every once in a while to pickup changes) to ensure it is available locally for future launch failures. If no `network_unavailable_url` is specified, then some sensible default "This app requires network connectivity" message would be rendered instead.

**Comment by marcoscaceres** [comment] 2015-03-23 18:13
This sounds like it should be handled by the app's service worker?

**Comment by skddc** [comment] 2015-03-23 18:24
Shouldn't it at least fail gracefully, when none has been defined?

**Comment by dvonlehman** [comment] 2015-03-23 18:27
Part of this could some technical ignorance, but if this is a hosted app rather than a packaged app, would there even be any JavaScript "installed" on the device to kick off the service worker?  Seems like such a fundamental use case that it would be nice if the manifest provided a nice abstraction so that every single app developer doesn't have to engineer the no network scenario from scratch.

**Comment by skddc** [comment] 2015-03-23 18:47
That's what the ServiceWorker is for, yes.

**Comment by marcoscaceres** [comment] 2015-03-23 18:49
@skddc: 
> Shouldn't it at least fail gracefully, when none has been defined?

This would just be normal browser 404 behavior - so yes, it would fail gracefully... or as gracefully as the UA can make it fail. 

> Part of this could some technical ignorance, but if this is a hosted app rather than a packaged app, would there even be any JavaScript "installed" on the device to kick off the service worker?

Note: Packaged apps are outside the scope of this spec. 

The working assumption is that this specification applies to web apps, not "hosted apps" (which have thus far been outside the scope of this specification).  By "hosted app" I'm assuming you mean a web application that a manufacturer has pre-installed on a device, but never actually run. 

Controversially, Mozilla is proposing supporting "hosted app" scenarios like the one you describe through: https://github.com/w3c/manifest/issues/161
 
> Seems like such a fundamental use case that it would be nice if the manifest provided a nice abstraction so that every single app developer doesn't have to engineer the no network scenario from scratch.

This only holds true if "hosted apps" are in scope for this specification. However, it does open up a whole bunch of issues if hosted apps are in scope of this specification (e.g., declaring CSP up front too).

**Comment by marcoscaceres** [comment] 2015-03-23 18:52
@dvonlehman I'm going to close this as a duplicate of #161. However, I will spin up a separate issue so we can discuss if "hosted apps" are in scope.

**Closed** 2015-03-23 18:52 UTC

**Comment by marcoscaceres** [comment] 2015-03-23 19:06
@skddc, you are also welcome to comment on #340

**Comment by dvonlehman** [comment] 2015-03-23 20:11
By "hosted apps" I'm referring to apps that are traditional web pages loaded from a remote URL. In this case the icon on the device is really a glorified bookmark. But it sounds like maybe the service worker acts as a shim that is copied down to the device upon app installation and is responsible for fetching any necessary remote assets including HTML, JavaScripts, stylesheets, or JSON payloads.

**Comment by skddc** [comment] 2015-03-23 20:18
Yes, you can cache app assets using a service worker and then only download updated assets in the background when opening an installed app for example.
